ValueSet:     Participants-DEV
Title:        "WHO GDHCN Trust Network Participant - DEV"
Description:  "ValueSet of GDHCN Trust Network Participants for Development environment"

* ^status = #active
* ^experimental = true

* include codes from system Participants-DEV


// To generate this list of codes for DEV environment
// execute the following on tng-participants-dev repo:
//     gfind . -maxdepth 1 -type d -name '[A-Z][A-Z][A-Z]' -printf "* \$RefMartCountryList#%P\n"  | grep -v WHO
//
// in the future, will need to exclude more than just WHO as not being from the RefMart set.

// This content will be generated by the enhanced generate_organizations.py script