ValueSet:     Participants-DEV
Title:        "WHO GDHCN Trust Network Participant - DEV"
Description:  "ValueSet of GDHCN Trust Network Participants for Development environment - includes all participants from DEV repository"

* ^status = #active
* ^experimental = true

* include codes from system Participants-DEV


// To generate this list of codes for DEV environment
// execute the following on tng-participants-dev repo:
//     gfind . -maxdepth 1 -type d -name '[A-Z][A-Z][A-Z]' -printf "* \$Participants-DEV#%P\n"  | grep -v WHO
//
// DEV environment includes ALL participants found in the DEV repository, 
// without any reference to RefMart list.

// This content will be generated by the enhanced generate_organizations.py script