@startuml
hide stereotype
!include <material/common>
!include <material/key>
!include <material/key_variant>

title Federated PKD Aggregation

left to right direction
package "Local PKD" as LP1 {
  MA_KEY(Black,1,pk1,rectangle,"Public Key")
}
package "Local PKD" as LP2 {
  MA_KEY_VARIANT(Black,1,pk2,rectangle,"Public Key")
}
package "Federated PKD"  as FPKD {
  package "Local PKD Mirror" as LP1M {
    MA_KEY(Black,1,pk1m,rectangle,"Public Key")
  }
  package "Local PKD Mirror" as LP2M {
    MA_KEY_VARIANT(Black,1,pk2m,rectangle,"Public Key")
  }
  package "Master List" as ML {
    MA_KEY(Black,1,pk1ml,rectangle,"Public Key")
    MA_KEY_VARIANT(Black,1,pk2ml,rectangle,"Public Key")
  }
}

pk1 --> pk1m
pk2 --> pk2m

pk1m -->pk1ml
pk2m --> pk2ml
@enduml