@startuml
hide stereotype
!include <material/common>
!include <material/key>
!include <material/key_variant>
!include <material/qrcode>
!include <material/ruler>

title Dynamic Business Rules Validation
left to right direction

package "[[system-actors.html#trust-network-anchor Trust Network\nAnchor]]" as TrustNetworkAnchor {
  package "Aggegated Trustist" as ML {
    MA_KEY(Black,1,pk1ml,rectangle,"[[system-actors.html#trust-network-participant Trust Network\nParticipant A]] Trustlist")
    MA_KEY_VARIANT(Black,1,pk2ml,rectangle,"[[system-actors.html#trust-network-participant Trust Network\nParticipant A]] Trustlist")
  }
  package "Business Rule Library"  as BRL {
    MA_RULER(Black,1,ruler,rectangle,"Business Rule")
  }
}

agent "[[system-actors.html#verifier Verifier]]" as Verifier
MA_QRCODE(Black,1,qr,rectangle,"Verificable Digital\nHealth Certificate")

pk1ml <-- Verifier : (Optional) Retrieve Business Rule Signing Key
ruler <-- Verifier : Retrieve Business Rule and (Optional) Verify Signature
Verifier --> qr : Deserialize, Verify Signature, and Extract FHIR Resources
Verifier --> qr : Execute Business Rule
@enduml
