@startuml

title Credential Issuance
hide footbox
participant "Credential Issuer" as CI
participant "Credential Holder" as Holder

group Issue Credential
    note over CI
    Credential Issuer constructs
    vaccine certificate from health data
    end note
    ...
    "CI" -> "Holder" : Provides vaccine certificate to individual
end
@enduml