@startuml

title Routine Synchronization
!include ./style.iuml
participant "Trust Network\nParticipant A" as TrustNetworkParticipantA
participant "Trust Network\nAnchor" as TrustNetworkAnchor
participant "Trust Network\nParticipant B" as TrustNetworkParticipantB



autonumber "<b>00:</b>"


loop routine synchronization
  activate TrustNetworkAnchor
  activate TrustNetworkParticipantA		
  TrustNetworkParticipantA -> TrustNetworkParticipantA : generate public-private key pairs
  TrustNetworkParticipantA -> TrustNetworkAnchor: send public keys			
  deactivate TrustNetworkParticipantA

  TrustNetworkAnchor -> TrustNetworkAnchor: Validate keys
  TrustNetworkAnchor -> TrustNetworkAnchor: Publish keys at distribution endpoints
  ... time passes ...		

  TrustNetworkParticipantB -> TrustNetworkAnchor: Retrieve keys
  deactivate TrustNetworkParticipantB
  deactivate TrustNetworkAnchor		 			
end

@enduml
