@startuml

title Routine Synchronization
!include ./style.iuml

participant "[[system-actors.html#trust-network-participant Trust Network\nParticipant A]]" as TrustNetworkParticipantA
participant "[[system-actors.html#trust-network-anchor Trust Network\nAnchor]]" as TrustNetworkAnchor
participant "[[system-actors.html#trust-network-participant Trust Network\nParticipant B]]" as TrustNetworkParticipantB



autonumber "<b>00:</b>"


loop routine synchronization
  activate TrustNetworkAnchor
  activate TrustNetworkParticipantA		
  TrustNetworkParticipantA -> TrustNetworkParticipantA : generate public-private key pairs
  TrustNetworkParticipantA -> TrustNetworkAnchor: [[transactions.html#publish_keys Publish Keys]]
  deactivate TrustNetworkParticipantA

  TrustNetworkAnchor -> TrustNetworkAnchor: Validate keys
  TrustNetworkAnchor -> TrustNetworkAnchor: Construct and sign trustlist of\nvalidated keys for distribution
  ... time passes ...		

  TrustNetworkParticipantB -> TrustNetworkAnchor: [[transactions.html#get_keys_did Retrieve Verification Keys]]
  deactivate TrustNetworkParticipantB
  deactivate TrustNetworkAnchor		 			
end

@enduml
