@startuml
hide stereotype
!include <material/common>
!include <material/key>
!include <material/key_variant>
!include <material/qrcode>

title Verification
left to right direction

package "Federated PKD"  as FPKD {
  package "Master List" as ML {
    MA_KEY(Black,1,pk1ml,rectangle,"Public Key")
    MA_KEY_VARIANT(Black,1,pk2ml,rectangle,"Public Key")
  }
}

agent "Verification Application" as VA
MA_QRCODE(Black,1,qr,rectangle,"Vaccine Credential")

pk1ml <-- VA : Retrieve Public Key
VA --> qr : Deserialize and Determine Key ID
VA --> qr : Verify Signature
@enduml