@startuml

title Verify a Digitial Health Certificate
!include ./style.iuml
participant "[[system-actors.html#trust-network-participant Trust Network\nParticipant]]" as TrustNetworkParticipant
participant "[[system-actors.html#issuer Issuer]]" as Issuer
participant "[[system-actors.html#holder Holder]]" as Holder
participant "[[system-actors.html#verifier Verifier]]" as Verifier


autonumber "<b>00:</b>"

TrustNetworkParticipant -> Issuer : designate as authorized issuer of \nVerifiable Digital Health\n Certificates (VDHCs)
Holder -> Issuer : request a VDHC
Issuer -> Holder : issue VDHC
Holder -> Verifier : provider VDHC
Verifier -> Verifier : extract signature, key id, and\nparticipant code from the VDHC
Verifier -> Verifier : lookup  Document Signing Certificate (DSC)\n public key by  key id and participant code
Verifier -> Verifier : verify signature using the public key

@enduml
