# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: smart.who.int.trust
canonical: http://smart.who.int/trust
name: trust
status: draft
version: 1.1.1
fhirVersion: 4.0.1
date: 2024-02-21
# copyright:
copyrightYear: 2023+
releaseLabel: "CI Build"
title: "WHO SMART Trust"
description: "SMART Trust Implementation Guide"
license: CC0-1.0
publisher:
  name: WHO
  url: http://who.int
email: tng-support@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:
    hl7.fhir.uv.ips: 1.1.0
#    fhir.who.ddcc: 1.0.0
#    who.ddcc: current
#    who.ips-pilgrimage: current
    who.ddcc: dev
    who.ips-pilgrimage: dev

pages:
  index.xml:
    title: Home
    changes.xml:
      title: Changes
    dependencies.xml:
      title: Dependencies
    references.xml:
      title: References
    adapting_guidelines.xml:
      title: Adapting Guidelines for Country use
    faq.md:
      title: Frequently Asked Questions
    requirements.xml:
      title: Business Requirements
    concepts.md:
      title: Concepts
      concepts_certificate_governance.md:
        title: Concepts Certificate Governance
      concepts_CertificatePreperation.md:
        title: Concepts Certificate Preparation
      concepts_did.md:
        title: Concepts Did
      concepts_governance.md:
        title: Concepts Governance
      concepts_onboarding.md:
        title: Concepts Onboarding
      concepts_onboarding_checklist.md:
        title: Concepts Onboarding Checklist
      concepts_onboarding_initialguideline_full.md:
        title: Concepts Onboarding Initial Guidance Full
      concepts_onboarding_initialprocess_full.md:
        title: Concepts Onboarding Initial Process Full
      concepts_onboarding_process_full.md:
        title: Concepts Onboarding Process Full
    use_cases.md:
      title: Use Cases
    decision_support.md:
      title: Decision Support Logic
    functional.md:
      title: Functional Requirements
  data_exchange.xml:
    title: Data Models and Exchange
    actors.md:
      title: System Actors
    transactions.md:
      title: Transactions
    workflows.md:
      title: Workflows
    content_profiles.md:                                                                                                                                                        
      title: Content profiles 
    hcert_spec.md:
      title: Electronic Health Certificate Specification
    trust_network_gateway_architecture.md:
      title: Trust Network Gateway Architecture
  deployment.xml:
    title: Deployment
    video_tutorial.md:
      title: Video Tutorials
    security_privacy.xml:
      title: Security and Privacy Considerations
    testing.xml: 
      title: Testing
    reference_implementation.md: 
      title: Reference Implementations
    downloads.xml: 
      title: Downloads
  indices.md:
    title: Indices
    artifacts.html: 
      title: Artifact Index
    maps.xml: 
      title: Mappings


menu:
  Home: 
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    References: references.html
    Adapting Guidelines for Country use: adapting_guidelines.html
    Frequently Asked Questions: faq.html
  Business Requirements: 
    Concepts: concepts.html
    Use Cases: use_cases.html
    Decision Support Logic: decision_support.html
    Functional Requirements: functional.html
  Data Models and Exchange:
    System Actors: actors.html
    Transactions: transactions.html
    Workflows: workflows.html
    Content Profiles: content_profiles.html
  Deployment:
    Video Tutorials: video_tutorial.html
    Security and Privacy Considerations: security_privacy.html
    Testing: testing.html
    Reference Implementations: reference_implementation.html
    Downloads: downloads.html
  Indices:
    Artifact Index: artifacts.html
    Mappings: maps.html
    