# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: smart.who.int.trust
canonical: http://smart.who.int/trust
name: Trust
experimental: false
status: draft
version: 1.1.6
fhirVersion: 5.0.0
# date: 2024-09-10
# copyright:
copyrightYear: 2023+
releaseLabel: "CI Build"
title: "WHO SMART Trust"
description: "SMART Trust Implementation Guide"
license: CC-BY-SA-3.0-IGO
publisher:
  name: WHO
  url: http://who.int
email: gdhcn-support@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true

special-url:
  - http://smart.who.int/refmart/CodeSystems/REF_COUNTRY

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

  produce-jekyll-data: true

  path-pages:
    - input/testing
    - input/tests/features
  path-binary:
    - input/tests/features
  path-test:
#    - input/tests/testplans
    - input/tests/features

meta:
  profile:
    - http://smart.who.int/base/StructureDefinition/SGImplementationGuide

dependencies:
#    hl7.fhir.uv.ips: 1.1.0
#    fhir.who.ddcc: 1.0.0
#    who.ddcc: current
#    smart.who.int.base: 0.1.0
    hl7.fhir.uv.extensions.r5: 5.2.0
    smart.who.int.base: current
    smart.who.int.trust-phw: current
    who.ddcc: current
    ihe.iti.mcsd: 
      id: IHE_ITI_mCSD
      uri: https://profiles.ihe.net/ITI/mCSD/ImplementationGuide/ihe.iti.mcsd 
      version: 3.8.0


      
pages:
  index.md:
    title: Home
    overview.md:
      title: Overview
    dependencies.md:
      title: Dependencies
    ethical_principles.md:
      title: Ethical Considerations and Data Protection Principles
    faq.md:
      title: Frequently Asked Questions
  business_requirements.md:
    title: Business Requirements
    concepts.md:
      title: Concepts
    concepts_certificate_governance.md:
      title: Certificate Governance
    concepts_onboarding.md:
      title: Onboarding Process
    use_cases.md:
      title: Use Cases
    decision_support.md:
      title: Decision Support Logic
    functional.md:
      title: Functional Requirements
  data_exchange.md:
    title: Data Models and Exchange
    system-actors.md:
      title: System Actors
    transactions.md:
      title: Transactions
    sequence-diagrams.md:
      title: Sequence Diagrams
    trust_domains.md:
      title: Trust Domains
    concepts_did.md:
      title: DID Trustlist Specification
      concepts_did_gdhcn.md:
        title: DID Trustlist v2 
      concepts_did_v1.md:
        title: DID Trustlist v1 (deprecated)      
    hcert_spec.md:
      title: HCERT Specification 
    trust_network_gateway_architecture.md:
      title: Trust Network Gateway Architecture
  deployment.md:
    title: Deployment
    concepts_onboarding_checklist.md:
      title: Onboarding Checklist
    security_privacy.md:
      title: Security and Privacy Considerations
    testing.md: 
      title: Testing
    test_cases.md:
      title: Test Cases
    reference_implementation.md: 
      title: Reference Implementations
    downloads.md: 
      title: Downloads
    changes.md:
      title: Changes      
    endpoints.md:
      title: Endpoints
  indices.md:
    title: Indices
    artifacts.html: 
      title: Artifact Index
    references.md:
      title: References
    maps.md: 
      title: Mappings
    license.md: 
      title: License
  #full_contents.md:
  #  title: Full Contents 




menu:
  Home: 
    Summary: index.html
    Dependencies: dependencies.html
    Ethical Considerations and Data Protection Principles: ethical_principles.html
    Frequently Asked Questions: faq.html
  Business Requirements: 
    Concepts: concepts.html    
    Certificate Governance: concepts_certificate_governance.html
    Onboarding Process: concepts_onboarding.html
    Use Cases: use_cases.html
    Decision Support Logic: decision_support.html
    Functional Requirements: functional.html
  Data Models and Exchange:
    System Actors: system-actors.html
    Transactions: transactions.html
    Sequence Diagrams: sequence-diagrams.html
    Trust Domains: trust_domains.html
    Trust Network Gateway Architecture: trust_network_gateway_architecture.html
    DID Trustlist Specification: concepts_did.html
    HCERT Specification: hcert_spec.html

  Deployment:
    Onboarding Checklist: concepts_onboarding_checklist.html
    Security and Privacy Considerations: security_privacy.html
    Testing: testing.html
    Test Cases: test_cases.html
    Reference Implementations: reference_implementation.html
    Downloads: downloads.html
    Changes: changes.html
    Endpoints: endpoints.html
  Indices:
    Artifact Index: artifacts.html
    References: references.html
    Mappings: maps.html
    License: license.html
