# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: smart.who.int.trust
canonical: http://smart.who.int/trust
name: Trust
experimental: false
status: draft
version: 1.1.6
fhirVersion: 5.0.0
# date: 2024-09-10
# copyright:
copyrightYear: 2023+
releaseLabel: "CI Build"
title: "WHO SMART Trust"
description: "SMART Trust Implementation Guide"
license: CC-BY-SA-3.0-IGO
publisher:
  name: WHO
  url: http://who.int
email: gdhcn-support@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true

meta:
  profile:
    - http://smart.who.int/base/StructureDefinition/SGImplementationGuide

dependencies:
#    hl7.fhir.uv.ips: 1.1.0
#    fhir.who.ddcc: 1.0.0
#    who.ddcc: current
#    smart.who.int.base: 0.1.0
    hl7.fhir.uv.extensions.r5: 5.2.0
    smart.who.int.base: current
    smart.who.int.trust-phw: current
    who.ddcc: current
    ihe.iti.mcsd: 
      id: IHE_ITI_mCSD
      uri: https://profiles.ihe.net/ITI/mCSD/ImplementationGuide/ihe.iti.mcsd 
      version: 3.8.0


      
pages:
  index.xml:
    title: Home
    overview.xml:
      title: Overview
    changes.xml:
      title: Changes
    dependencies.xml:
      title: Dependencies
    ethical_principles.md:
      title: Ethical Considerations and Data Protection Principles
    references.xml:
      title: References
    adapting_guidelines.xml:
      title: Adapting Guidelines for Country use
    faq.md:
      title: Frequently Asked Questions
    requirements.xml:
      title: Business Requirements
    concepts_overview.md:
      title: Concepts
      concepts.md:
        title: Concepts Glossary
      concepts_certificate_governance.md:
        title: Concepts Certificate Governance
      concepts_CertificatePreperation.md:
        title: Concepts Certificate Preparation
      concepts_onboarding.md:
        title: Concepts Onboarding
      concepts_onboarding_initialguideline_full.md:
        title: Concepts Onboarding Initial Guidance Full
      concepts_onboarding_initialprocess_full.md:
        title: Concepts Onboarding Initial Process Full
      concepts_onboarding_process_full.md:
        title: Concepts Onboarding Process Full
    use_cases.md:
      title: Use Cases
    decision_support.md:
      title: Decision Support Logic
    functional.md:
      title: Functional Requirements
  data_exchange.xml:
    title: Data Models and Exchange
    actors.md:
      title: System Actors
    transactions.md:
      title: Transactions
    workflows.md:
      title: Workflows
    trust_domains.md:
      title: Trust Domains
    concepts_did.md:
      title: Concepts DID
      concepts_did_gdhcn.md:
        title: Concepts GDHCN Trust List
      concepts_did_v1.md:
        title: Concepts v1      
    hcert_spec.md:
      title: HCERT Specification 
    trust_network_gateway_architecture.md:
      title: Trust Network Gateway Architecture
  deployment.xml:
    title: Deployment
    concepts_onboarding_checklist.md:
      title: Concepts Onboarding Checklist
    security_privacy.xml:
      title: Security and Privacy Considerations
    testing.xml: 
      title: Testing
    reference_implementation.md: 
      title: Reference Implementations
    downloads.xml: 
      title: Downloads
    endpoints.md:
      title: Endpoints
  indices.md:
    title: Indices
    artifacts.html: 
      title: Artifact Index
    maps.xml: 
      title: Mappings
  license.md: 
    title: License
  full_contents.md:
    title: Full Contents 


menu:
  Home: 
    Summary: index.html
    Changes: changes.html
    Dependencies: dependencies.html
    Ethical Considerations and Data Protection Principles: ethical_principles.html
    Frequently Asked Questions: faq.html
  Business Requirements: 
    Concepts: concepts.html
    Use Cases: use_cases.html
    Decision Support Logic: decision_support.html
    Functional Requirements: functional.html
  Data Models and Exchange:
    System Actors: actors.html
    Transactions: transactions.html
    Workflows: workflows.html
    Trust Domains: trust_domains.html
    Trust Network Gateway Architecture: trust_network_gateway_architecture.html
    DID Trust Lists: concepts_did.html
    HCERT Specification: hcert_spec.html

  Deployment:
    Onboarding: concepts_onboarding_checklist.html
    Security and Privacy Considerations: security_privacy.html
    Testing: testing.html
    Reference Implementations: reference_implementation.html
    Downloads: downloads.html
    Adapting Guidelines for Country use: adapting_guidelines.html
    References: references.html
    Endpoints: endpoints.html
  Indices:
    Artifact Index: artifacts.html
    References: references.html
    Mappings: maps.html
    Changes: changes.html
    Downloads: downloads.html
    License: license.html


    
