# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: smart.who.int.trust
canonical: http://smart.who.int/trust
name: trust
status: active
version: 1.0.0
fhirVersion: 4.0.1
date: 2024-01-26
# copyright:
copyrightYear: 2023+
releaseLabel: "1.0.0"
title: "WHO SMART Trust"
description: "SMART Trust Implementation Guide"
license: CC0-1.0
publisher:
  name: WHO
  url: http://who.int
email: tng-support@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies:
    hl7.fhir.uv.ips: 1.1.0
#    fhir.who.ddcc: 1.0.0
#    who.ddcc: current
#    who.ips-pilgrimage: current
    who.ddcc: dev
    who.ips-pilgrimage: dev
    
