# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.who.smart-trust
canonical: http://worldhealthorganization.github.io/smart-trust
name: smart-trust
status: draft
version: 0.0.1
fhirVersion: 5.0.0
date: 2023-02-15
# copyright:
copyrightYear: 2023+
releaseLabel: "CI Build"
title: "WHO SMART Trust"
description: "SMART Trust Implementation Guide"
license: CC0-1.0
publisher:
  name: WHO
  url: http://who.int
email: leitnerc@who.int
# contact:
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001
# experimental: true
dependencies: { "IHE.ITI.mCSD" : "3.8.0" }