id: smart.who.int.trust
canonical: http://smart.who.int/trust
name: Trust
experimental: false
status: draft
version: 1.1.6
fhirVersion: 5.0.0
copyrightYear: 2023+
releaseLabel: "CI Build"
title: "WHO SMART Trust"
description: "SMART Trust Implementation Guide"
license: CC-BY-SA-3.0-IGO
publisher:
  name: WHO
  url: http://who.int

parameters:
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  produce-jekyll-data: true

# Minimal dependencies for testing
dependencies:
  # Remove problematic dependencies temporarily for testing