name: "📢 Feedback"
description: Provide feedback about specific sections of the implementation guide.
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: input
    id: page
    attributes:
      label: Page URL
      description: "Link to the page you're giving feedback on (auto-filled)."
      placeholder: "e.g., https://your-ig.org/medication/page.html#section"
    validations:
      required: true

  - type: input
    id: section
    attributes:
      label: Section
      description: "Name of the section your feedback relates to."
      placeholder: "e.g., Medication Dispensing"
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Feedback Description
      description: "Please describe your feedback in detail."
      placeholder: "Describe the issue, suggestion, or improvement clearly..."
    validations:
      required: true
