CodeSystem: Participants-DEV
Title: "WHO GDHCN Trust Network Participant - DEV"
Description: "CodeSystem for GDHCN Trust Network Participants for Development environment"
* ^experimental = true
* ^caseSensitive = false
* ^url = "http://smart.who.int/trust/CodeSystems/Participants-DEV"
* #AND "AND"
* #ARG "ARG"
* #ARM "ARM"
* #BHS "BHS"
* #BLZ "BLZ"
* #BRA "BRA"
* #BRB "BRB"
* #CHL "CHL"
* #COL "COL"
* #CRI "CRI"
* #CYP "CYP"
* #DOM "DOM"
* #ECU "ECU"
* #EST "EST"
* #GTM "GTM"
* #HND "HND"
* #IDN "IDN"
* #LVA "LVA"
* #OMN "OMN"
* #PAN "PAN"
* #PER "PER"
* #PRY "PRY"
* #SGP "SGP"
* #SLV "SLV"
* #SMR "SMR"
* #SUR "SUR"
* #SVN "SVN"
* #TGO "TGO"
* #URY "URY"
* #USA "USA"
* #XCL "XCL"
* #XML "XML"
* #XXA "XXA"
* #XXB "XXB"
* #XXC "XXC"
* #XXD "XXD"
* #XXE "XXE"
* #XXF "XXF"
* #XXG "XXG"
* #XXH "XXH"
* #XXI "XXI"
* #XXJ "XXJ"
* #XXK "XXK"
* #XXO "XXO"
* #XXP "XXP"
* #XXU "XXU"
* #XXV "XXV"
* #XXX "XXX"
* #XYK "XYK"

