CodeSystem: Participants-DEV
Title: "WHO GDHCN Trust Network Participant - DEV"
Description: "CodeSystem for GDHCN Trust Network Participants for Development environment"
* ^experimental = true
* ^caseSensitive = false
* ^url = "http://smart.who.int/trust/CodeSystems/Participants-DEV"
* #AND "DEV Participant AND"
* #ARG "DEV Participant ARG"
* #ARM "DEV Participant ARM"
* #BHS "DEV Participant BHS"
* #BLZ "DEV Participant BLZ"
* #BRA "Brasília"
* #BRB "DEV Participant BRB"
* #CHL "DEV Participant CHL"
* #COL "DEV Participant COL"
* #CRI "DEV Participant CRI"
* #CYP "DEV Participant CYP"
* #DOM "DEV Participant DOM"
* #ECU "DEV Participant ECU"
* #EST "DEV Participant EST"
* #GTM "DEV Participant GTM"
* #HND "DEV Participant HND"
* #IDN "DEV Participant IDN"
* #LVA "DEV Participant LVA"
* #OMN "DEV Participant OMN"
* #PAN "DEV Participant PAN"
* #PER "DEV Participant PER"
* #PRY "DEV Participant PRY"
* #SGP "DEV Participant SGP"
* #SLV "DEV Participant SLV"
* #SMR "DEV Participant SMR"
* #SUR "DEV Participant SUR"
* #SVN "DEV Participant SVN"
* #TGO "DEV Participant TGO"
* #URY "DEV Participant URY"
* #USA "Washington"
* #XCL "DEV Participant XCL"
* #XML "DEV Participant XML"
* #XXA "Test City Alpha"
* #XXB "Test City Beta"
* #XXC "Test City Gamma"
* #XXD "Test City Delta"
* #XXE "DEV Participant XXE"
* #XXF "DEV Participant XXF"
* #XXG "DEV Participant XXG"
* #XXH "DEV Participant XXH"
* #XXI "DEV Participant XXI"
* #XXJ "DEV Participant XXJ"
* #XXK "DEV Participant XXK"
* #XXO "Test City Omega"
* #XXP "DEV Participant XXP"
* #XXU "Test City Upsilon"
* #XXV "Test City Phi"
* #XXX "Test City Chi"
* #XYK "Test City Psi"

