CodeSystem: Participants-DEV
Title: "WHO GDHCN Trust Network Participant - DEV"
Description: "CodeSystem for GDHCN Trust Network Participants for Development environment"
* ^experimental = true
* ^caseSensitive = false
* ^url = "http://smart.who.int/trust/CodeSystems/Participants-DEV"
* #IOM "TEST"
* #WHO "DEV Participant WHO"
* #XCL "California"
* #XML "GDHCN entomo"
* #XXA "Geneva"
* #XXB "TEST"
* #XXC "TEST"
* #XXD "CENS XD"
* #XXE "Geneva XE"
* #XXF "Test Locality XF"
* #XXG "Geneva"
* #XXH "Geneva"
* #XXI "California"
* #XXJ "DEV Participant XXJ"
* #XXK "Rengo"
* #XXN "DEV Participant XXN"
* #XXO "DEV Participant XXO"
* #XXP "Geneva"
* #XXQ "Test Locality"
* #XXT "Geneva"
* #XXU "Geneva"
* #XXV "Test city"
* #XXW "Test Locality"
* #XXX "Warrandyte"
* #XYK "Test"

