name: Trigger WHO SMART Trust Update (GitHub App)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      force_environment:
        description: 'Force specific environment (leave empty for auto-detection)'
        required: false
        type: choice
        options:
        - ''
        - PROD
        - UAT
        - DEV

jobs:
  trigger-smart-trust-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Determine environment
      id: env
      run: |
        REPO_NAME="${{ github.repository }}"
        
        # Use manual input if provided
        if [ -n "${{ github.event.inputs.force_environment }}" ]; then
          ENV="${{ github.event.inputs.force_environment }}"
        else
          # Auto-detect from repository name (part after last dash)
          ENV_SUFFIX=$(echo "$REPO_NAME" | sed 's/.*-//')
          ENV=$(echo "$ENV_SUFFIX" | tr '[:lower:]' '[:upper:]')
        fi
        
        echo "environment=$ENV" >> $GITHUB_OUTPUT
        echo "Detected environment: $ENV for repository: $REPO_NAME"
        
    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.WHO_SMART_TRUST_APP_ID }}
        private-key: ${{ secrets.WHO_SMART_TRUST_PRIVATE_KEY }}
        repositories: smart-trust
        
    - name: Trigger WHO SMART Trust participant generation
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ steps.app-token.outputs.token }}
        repository: WorldHealthOrganization/smart-trust
        event-type: participant-update
        client-payload: |
          {
            "environment": "${{ steps.env.outputs.environment }}",
            "source_repository": "${{ github.repository }}",
            "triggered_by": "${{ github.actor }}",
            "commit_sha": "${{ github.sha }}",
            "ref": "${{ github.ref }}",
            "timestamp": "${{ github.event.head_commit.timestamp }}",
            "auth_method": "github_app"
          }
          
    - name: Log webhook trigger
      run: |
        echo "Successfully triggered WHO SMART Trust update using GitHub App"
        echo "Environment: ${{ steps.env.outputs.environment }}"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
        echo "Authentication: GitHub App (secure)"