openapi: 3.0.3
info:
  title: Health Certificate API
  description: Logical Model for the HCERT
  version: 1.0.0
paths:
  /StructureDefinition-HCert.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-HCert
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-HCert.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-HCert
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-HCert.schema.json
components:
  schemas:
    StructureDefinition-HCert:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/trust/StructureDefinition-HCert.schema.json
      title: Health Certificate
      description: Logical Model for the HCERT
      type: object
      properties:
        '1':
          $ref: http://smart.who.int/ddcc/StructureDefinition-HCertDCC.schema.json
          description: HCERT EU DCC
        '3':
          type: array
          items:
            $ref: http://smart.who.int/ddcc/StructureDefinition-DDCCCoreDataSet.schema.json
          description: DDCC Vaccination claim (PROPOSED)
        '4':
          type: array
          items:
            $ref: http://smart.who.int/ddcc/StructureDefinition-DDCCCoreDataSet.schema.json
          description: DDCC Test Result claim (PROPOSED)
        '5':
          type: array
          items:
            type: string
          description: URI of the Smart Health Link.  Of the form 'shlink:/eyJ1cmwiOiJodHRwczovL2Vo....'
        '-6':
          type: array
          items:
            $ref: http://smart.who.int/trust-phw/StructureDefinition-DVC.schema.json
          description: Digital Vaccination Certificate (Proposed)
      required: []
      fhir:logicalModel: http://smart.who.int/trust/StructureDefinition/HCert
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
