openapi: 3.0.3
info:
  title: Scheme Information API
  description: Logical Model for Information on the trusted list and its issuing scheme
  version: 1.0.0
paths:
  /StructureDefinition-SchemeInformation.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-SchemeInformation
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-SchemeInformation.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-SchemeInformation
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-SchemeInformation.schema.json
components:
  schemas:
    StructureDefinition-SchemeInformation:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/trust/StructureDefinition-SchemeInformation.schema.json
      title: Scheme Information
      description: Logical Model for Information on the trusted list and its issuing
        scheme
      type: object
      properties:
        versionIdentifier:
          type: integer
          description: TSL version identifier (clause 5.3.1)
        sequenceNumber:
          type: integer
          description: TSL sequence number (clause 5.3.2)
        type:
          type: string
          format: uri
          description: TSL type (clause 5.3.3)
        operatorName:
          type: string
          description: Scheme operator name (clause 5.3.4)
        operatorAddress:
          type: array
          items:
            type: object
            description: FHIR BackboneElement
          minItems: 1
          description: Scheme operator address (clause 5.3.5)
        id:
          type: object
          description: Unique id for the element within a resource (for internal references).
            This may be any string value that does not contain spaces.
        modifierExtension:
          type: array
          items:
            type: object
            description: FHIR Extension
          description: 'May be used to represent additional information that is not
            part of the basic definition of the element and that modifies the understanding
            of the element in which it is contained and/or the understanding of the
            containing element''s descendants. Usually modifier elements provide negation
            or qualification. To make the use of extensions safe and manageable, there
            is a strict set of governance applied to the definition and use of extensions.
            Though any implementer can define an extension, there is a set of requirements
            that SHALL be met as part of the definition of the extension. Applications
            processing a resource are required to check for modifier extensions.


            Modifier extensions SHALL NOT change the meaning of any elements on Resource
            or DomainResource (including cannot change the meaning of modifierExtension
            itself).'
        operatorPostalAddress:
          type: array
          items:
            type: object
          minItems: 1
          description: Scheme Operator Postal Address
        operatorElectronicAddress:
          type: array
          items:
            type: object
          description: Scheme Operator Electronic Address
        name:
          type: string
          description: Scheme name (clause 5.3.6) CC:EN_name_value
        informationURI:
          type: string
          format: uri
          description: Scheme information URI (clause 5.3.7)
        statusDeterminiationApproach:
          type: string
          format: uri
          description: Status determination approach (clause 5.3.8)
        schemeType:
          type: string
          format: uri
          description: Scheme type/community/rules (clause 5.3.9)
        territory:
          type: string
          description: Scheme territory (clause 5.3.10)
        policy:
          type: string
          format: uri
          description: TSL policy/legal notice (clause 5.3.11)
        historicalInformationPeriod:
          type: integer
          description: Historical information period (clause 5.3.12)
        otherTSL:
          type: array
          items:
            type: string
          description: Pointers to other TSLs (clause 5.3.13)
        issDateTime:
          type: string
          format: date-time
          description: List issue date and time (clause 5.3.14)
        nextUpdate:
          type: string
          format: date-time
          description: Next update (clause 5.3.15)
        distributionPoints:
          type: array
          items:
            type: string
            format: uri
          description: Distribution points (clause 5.3.16)
      required:
      - versionIdentifier
      - sequenceNumber
      - type
      - operatorName
      - operatorAddress
      - operatorPostalAddress
      - name
      - informationURI
      - statusDeterminiationApproach
      - schemeType
      - territory
      - policy
      - historicalInformationPeriod
      - issDateTime
      - nextUpdate
      fhir:logicalModel: http://smart.who.int/trust/StructureDefinition/SchemeInformation
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
